### ISSUE TITLE
Documentation or Sample Project?

### ISSUE THREAD

**Issue by thepigeonfighter** [bbsimonbb/query-first#68]
Hey there, was curious if you had a sample project that uses this extension since the documentation is so sparse. I've spun up a console application to use this and so far its been pretty amazing, I'd just like to see some examples thanks for all the hard work! 

The initial question I am having is considering data models. Are there ways to reuse a generated model in a different query or is a new model created on a per query basis?

**Comment by AdrianBathurst** [comment]
Yeap, documentation is sparse, so doesn't show off just how good it is. Saying that, it's also incredibly simple so doesn't need much.

Here are some bits put together:

http://geniusorfantasist.blogspot.com/2017/02/the-tool-in-action.html

https://www.youtube.com/channel/UC2Qks7tf0jo-Nhtc8FBzXOQ

https://marketplace.visualstudio.com/items?itemName=bbsimonbb.QueryFirst

https://github.com/bbsimonbb/query-first/wiki

https://www.codeproject.com/Tips/1108776/Your-SQL-Wrapped-in-Generated-Code-Interesting-Ori

**Comment by AdrianBathurst** [comment]
Attached is a project with some sample queries.

Attach the project's database that's in `/db`

Edit `QfRuntimeConnection.cs` and `qfconfig.json` with your database connection string.

Re-apply the nuget `/packages` (there's only one). _Had to delete it to reduce the zip size so it could be attached._

See samples in Global.asax

[QF_Test.zip](https://github.com/bbsimonbb/query-first/files/6450849/QF_Test.zip)

**Comment by thepigeonfighter** [comment]
Thanks for these resources! The test project is helpful to see different scenarios. I'm investigating this project to use commercially. While I agree that it is incredibly simple to use (props to you!) I feel like in order to be confident to use the project there should be some additional documentation added around some key things 
- Supported database types
- Self tests? (had seen this referred to but couldn't find examples anywhere)
- Is there anything that this extension can't do in SQL for whatever reason?
- Suggested project structure (to me it kind of seems best to create a query project that is by itself since this plugin is doing the job of multiple application layers)
-  Config file options(I saw several handy options in videos but it'd be good to know all the options)
-  How do you handle encrypted connection strings?  For example our connection strings are never stored in the clear in config files but always need to be decrypted first. There doesn't seem to be a way to accommodate for that with this extension? 

Overall I've been impressed with the tooling and the quality of this product. I hope it gets some more attention in the future, just would like  to get more info before I attempt to integrate it with a production project and run into something I didn't realize was a limitation.  If I do end up using this project and getting more familiar with it. I could help write the documentation (if you're interested) as I imagine just maintaining this project is enough of a burden.

**Comment by bbsimonbb** [comment]
Hi George, first up thanks for your interest. Using a little-known data access lib commercially might strike some as brave, but here are some points:

- The project is actively maintained and there are no blocking issues outstanding. The current focus is on fusing the VS extension with the command line tool I wrote for VS Code. Soon (hopefully) the same version of QueryFirst will run everywhere, and soon after, it will generate java, asynch C# and whatever else you're having.
- Since QueryFirst is not a dependency, you will never be cornered. You can inspect the generated code, and if you're really stuck, you can disactivate regeneration and fix any problems by hand. No one has ever had to do this that I know of.
- Since 2017, QueryFirst supports SQL Server, Postgres and MySql. With Postgres, we can't handle user defined types, and with MySql you have to declare your parameter types if you want strongly typed inputs. Those are the main limitations that spring to mind. Also, we can't currently handle statements that have side effects, such as the creation of temp tables. Automated testing doesn't currently cover Postgres and MySql.

Addressing your questions...
- SelfTest documentation: I'll get right onto it. It's very simple.
- Limitations: see above
- Project Structure: my views on this could get me arrested. N-tier is a disaster, and a reusable DAL a fantasy. Don't create abstractions til you need them. Files you open together should live together. When queries are easy to write and maintain, you can write more, more specialised queries, and so operate on simpler, less voluminous objects and object graphs. I like projects structured vertically, and I'm not shocked by a SQL query sitting next to an API controller in a folder named after a use case.
- In your first post, you asked about queries sharing a data model. Sometimes (not that often), you want to do the same operation on the output of more than one query. In that case, use interfaces. Tag each of the result classes with the interface, and if ever a query no longer conforms to it's interface, it will pop out when you regenerate the query. In VS, do this in the user partial class.

Please leave a review as soon as you feel you know you're way around!

**Comment by thepigeonfighter** [comment]
Great! thanks for the insight. This all makes sense to me.  Any guidance on the connection strings? I think if we can get that sorted I think i'll be able to convince folks to give it a shot.

**Comment by bbsimonbb** [comment]
Connection strings. The design time connection string has to be in the clear in qfconfig.json, but this shouldn't be a security problem. This should point a development DB, and it's present only in the app source (the build action on your qfconfig.json should be "do not copy"). As an additional measure, you could keep qfconfig.json out of source control?

For runtime db connections, you are responsible for the QfRuntimeConnection class, so put in their whatever logic you need to access your connection strings. QueryFirst makes no demands about where runtime connection info comes from.
