### ISSUE TITLE
Location of generated files

### ISSUE THREAD

**Issue by jandnil** [bbsimonbb/query-first#79]
Is it possible to configure the generated files in such a way that results --> to some "result" folder and XXX.gen.cs --> some name "generated" folder? My goal is to  just keep things clean and tidy i would like to have 3 folders one for queries , one for result classes and one for the generated folders and make sure that every time a new query is added the generated the files end up in the same per-determined folders. 

And last but not least very good tool and great work!

**Comment by AdrianBathurst** [comment]
Interesting idea, but nope. It's already clean and tidy with the cs files nested under the sql file.

**Comment by bbsimonbb** [comment]
You really want the generated file nested under the .sql. For renaming, for deleting, for understanding that it's a totally dependent thing. The reason I'm ready to hear would be if you wanted the DTOs in a separate project, so as to publish them as a nuget, because they're the return types of your API ???

[Here's a very old discussion](https://softwareengineering.stackexchange.com/questions/310833/why-does-everyone-put-controllers-in-one-folder-and-views-in-another) on the what belongs in the same folder, if you've time. I'm really for keeping together the files that you're likely to open together, the files that one day you'll delete together. My queries are right there next to my api controllers in a folder named after the use case, and it works very well.

Closing...
